//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Name2
    extends JAXBElement<String>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "name");

    public Name2(String value) {
        super(NAME, ((Class) String.class), null, value);
    }

}
