//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;
import org.gpx2web.binding.kml.impl.SnippetTypeImpl;

public class Snippet2
    extends JAXBElement<SnippetType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "Snippet");

    public Snippet2(SnippetTypeImpl value) {
        super(NAME, ((Class) SnippetTypeImpl.class), null, value);
    }

}
