//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractContainerType;
import org.gpx2web.binding.kml.AbstractObjectType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractContainerType", propOrder = {
    "abstractContainerSimpleExtensionGroups",
    "abstractContainerObjectExtensionGroups"
})
@XmlSeeAlso({
    DocumentTypeImpl.class,
    FolderTypeImpl.class
})
public abstract class AbstractContainerTypeImpl
    extends AbstractFeatureTypeImpl
    implements AbstractContainerType
{

    @XmlElement(name = "AbstractContainerSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> abstractContainerSimpleExtensionGroups;
    @XmlElement(name = "AbstractContainerObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> abstractContainerObjectExtensionGroups;

    public List<Object> getAbstractContainerSimpleExtensionGroups() {
        if (abstractContainerSimpleExtensionGroups == null) {
            abstractContainerSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.abstractContainerSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getAbstractContainerObjectExtensionGroups() {
        if (abstractContainerObjectExtensionGroups == null) {
            abstractContainerObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.abstractContainerObjectExtensionGroups;
    }

}
