//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.AbstractViewType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractViewType", propOrder = {
    "abstractViewSimpleExtensionGroups",
    "abstractViewObjectExtensionGroups"
})
@XmlSeeAlso({
    CameraTypeImpl.class,
    LookAtTypeImpl.class
})
public abstract class AbstractViewTypeImpl
    extends AbstractObjectTypeImpl
    implements AbstractViewType
{

    @XmlElement(name = "AbstractViewSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> abstractViewSimpleExtensionGroups;
    @XmlElement(name = "AbstractViewObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> abstractViewObjectExtensionGroups;

    public List<Object> getAbstractViewSimpleExtensionGroups() {
        if (abstractViewSimpleExtensionGroups == null) {
            abstractViewSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.abstractViewSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getAbstractViewObjectExtensionGroups() {
        if (abstractViewObjectExtensionGroups == null) {
            abstractViewObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.abstractViewObjectExtensionGroups;
    }

}
