//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractLatLonBoxType;
import org.gpx2web.binding.kml.AbstractObjectType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractLatLonBoxType", propOrder = {
    "north",
    "south",
    "east",
    "west",
    "abstractLatLonBoxSimpleExtensionGroups",
    "abstractLatLonBoxObjectExtensionGroups"
})
@XmlSeeAlso({
    LatLonBoxTypeImpl.class,
    LatLonAltBoxTypeImpl.class
})
public abstract class AbstractLatLonBoxTypeImpl
    extends AbstractObjectTypeImpl
    implements AbstractLatLonBoxType
{

    @XmlElement(defaultValue = "180.0")
    protected Double north;
    @XmlElement(defaultValue = "-180.0")
    protected Double south;
    @XmlElement(defaultValue = "180.0")
    protected Double east;
    @XmlElement(defaultValue = "-180.0")
    protected Double west;
    @XmlElement(name = "AbstractLatLonBoxSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> abstractLatLonBoxSimpleExtensionGroups;
    @XmlElement(name = "AbstractLatLonBoxObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> abstractLatLonBoxObjectExtensionGroups;

    public Double getNorth() {
        return north;
    }

    public void setNorth(Double value) {
        this.north = value;
    }

    public Double getSouth() {
        return south;
    }

    public void setSouth(Double value) {
        this.south = value;
    }

    public Double getEast() {
        return east;
    }

    public void setEast(Double value) {
        this.east = value;
    }

    public Double getWest() {
        return west;
    }

    public void setWest(Double value) {
        this.west = value;
    }

    public List<Object> getAbstractLatLonBoxSimpleExtensionGroups() {
        if (abstractLatLonBoxSimpleExtensionGroups == null) {
            abstractLatLonBoxSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.abstractLatLonBoxSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getAbstractLatLonBoxObjectExtensionGroups() {
        if (abstractLatLonBoxObjectExtensionGroups == null) {
            abstractLatLonBoxObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.abstractLatLonBoxObjectExtensionGroups;
    }

}
