//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractFeatureType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.FolderType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FolderType", propOrder = {
    "abstractFeatureGroups",
    "folderSimpleExtensionGroups",
    "folderObjectExtensionGroups"
})
public class FolderTypeImpl
    extends AbstractContainerTypeImpl
    implements FolderType
{

    @XmlElementRef(name = "AbstractFeatureGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractFeatureType>> abstractFeatureGroups;
    @XmlElement(name = "FolderSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> folderSimpleExtensionGroups;
    @XmlElement(name = "FolderObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> folderObjectExtensionGroups;

    public List<JAXBElement<? extends AbstractFeatureType>> getAbstractFeatureGroups() {
        if (abstractFeatureGroups == null) {
            abstractFeatureGroups = new ArrayList<JAXBElement<? extends AbstractFeatureType>>();
        }
        return this.abstractFeatureGroups;
    }

    public List<Object> getFolderSimpleExtensionGroups() {
        if (folderSimpleExtensionGroups == null) {
            folderSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.folderSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getFolderObjectExtensionGroups() {
        if (folderObjectExtensionGroups == null) {
            folderObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.folderObjectExtensionGroups;
    }

}
