//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.BasicLinkType;
import org.gpx2web.binding.kml.IconStyleType;
import org.gpx2web.binding.kml.Vec2Type;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IconStyleType", propOrder = {
    "scale",
    "heading",
    "icon",
    "hotSpot",
    "iconStyleSimpleExtensionGroups",
    "iconStyleObjectExtensionGroups"
})
public class IconStyleTypeImpl
    extends AbstractColorStyleTypeImpl
    implements IconStyleType
{

    @XmlElement(defaultValue = "1.0")
    protected Double scale;
    @XmlElement(defaultValue = "0.0")
    protected Double heading;
    @XmlElement(name = "Icon", type = BasicLinkTypeImpl.class)
    protected BasicLinkTypeImpl icon;
    @XmlElement(type = Vec2TypeImpl.class)
    protected Vec2TypeImpl hotSpot;
    @XmlElement(name = "IconStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> iconStyleSimpleExtensionGroups;
    @XmlElement(name = "IconStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> iconStyleObjectExtensionGroups;

    public Double getScale() {
        return scale;
    }

    public void setScale(Double value) {
        this.scale = value;
    }

    public Double getHeading() {
        return heading;
    }

    public void setHeading(Double value) {
        this.heading = value;
    }

    public BasicLinkType getIcon() {
        return icon;
    }

    public void setIcon(BasicLinkType value) {
        this.icon = ((BasicLinkTypeImpl) value);
    }

    public Vec2Type getHotSpot() {
        return hotSpot;
    }

    public void setHotSpot(Vec2Type value) {
        this.hotSpot = ((Vec2TypeImpl) value);
    }

    public List<Object> getIconStyleSimpleExtensionGroups() {
        if (iconStyleSimpleExtensionGroups == null) {
            iconStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.iconStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getIconStyleObjectExtensionGroups() {
        if (iconStyleObjectExtensionGroups == null) {
            iconStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.iconStyleObjectExtensionGroups;
    }

}
