//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LabelStyleType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelStyleType", propOrder = {
    "scale",
    "labelStyleSimpleExtensionGroups",
    "labelStyleObjectExtensionGroups"
})
public class LabelStyleTypeImpl
    extends AbstractColorStyleTypeImpl
    implements LabelStyleType
{

    @XmlElement(defaultValue = "1.0")
    protected Double scale;
    @XmlElement(name = "LabelStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> labelStyleSimpleExtensionGroups;
    @XmlElement(name = "LabelStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> labelStyleObjectExtensionGroups;

    public Double getScale() {
        return scale;
    }

    public void setScale(Double value) {
        this.scale = value;
    }

    public List<Object> getLabelStyleSimpleExtensionGroups() {
        if (labelStyleSimpleExtensionGroups == null) {
            labelStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.labelStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getLabelStyleObjectExtensionGroups() {
        if (labelStyleObjectExtensionGroups == null) {
            labelStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.labelStyleObjectExtensionGroups;
    }

}
