//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.namespace.QName;
import org.gpx2web.binding.kml.AddressLine;
import org.gpx2web.binding.kml.DependentLocalityType;
import org.gpx2web.binding.kml.LargeMailUserType;
import org.gpx2web.binding.kml.Locality;
import org.gpx2web.binding.kml.PostBox;
import org.gpx2web.binding.kml.PostOffice;
import org.gpx2web.binding.kml.PostalCode;
import org.gpx2web.binding.kml.PostalRouteType;
import org.gpx2web.binding.kml.Premise;
import org.gpx2web.binding.kml.Thoroughfare;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressLines",
    "localityNames",
    "postalRoute",
    "postOffice",
    "largeMailUser",
    "postBox",
    "thoroughfare",
    "premise",
    "dependentLocality",
    "postalCode",
    "anies"
})
@XmlRootElement(name = "Locality", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0")
public class LocalityImpl
    implements Locality
{

    @XmlElement(name = "AddressLine", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = AddressLineImpl.class)
    protected List<AddressLine> addressLines;
    @XmlElement(name = "LocalityName", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = LocalityImpl.LocalityNameImpl.class)
    protected List<Locality.LocalityName> localityNames;
    @XmlElement(name = "PostalRoute", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PostalRouteTypeImpl.class)
    protected PostalRouteTypeImpl postalRoute;
    @XmlElement(name = "PostOffice", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PostOfficeImpl.class)
    protected PostOfficeImpl postOffice;
    @XmlElement(name = "LargeMailUser", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = LargeMailUserTypeImpl.class)
    protected LargeMailUserTypeImpl largeMailUser;
    @XmlElement(name = "PostBox", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PostBoxImpl.class)
    protected PostBoxImpl postBox;
    @XmlElement(name = "Thoroughfare", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = ThoroughfareImpl.class)
    protected ThoroughfareImpl thoroughfare;
    @XmlElement(name = "Premise", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseImpl.class)
    protected PremiseImpl premise;
    @XmlElement(name = "DependentLocality", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = DependentLocalityTypeImpl.class)
    protected DependentLocalityTypeImpl dependentLocality;
    @XmlElement(name = "PostalCode", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PostalCodeImpl.class)
    protected PostalCodeImpl postalCode;
    @XmlAnyElement(lax = true)
    protected List<Object> anies;
    @XmlAttribute(name = "Type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute(name = "UsageType")
    @XmlSchemaType(name = "anySimpleType")
    protected String usageType;
    @XmlAttribute(name = "Indicator")
    @XmlSchemaType(name = "anySimpleType")
    protected String indicator;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    public List<AddressLine> getAddressLines() {
        if (addressLines == null) {
            addressLines = new ArrayList<AddressLine>();
        }
        return this.addressLines;
    }

    public List<Locality.LocalityName> getLocalityNames() {
        if (localityNames == null) {
            localityNames = new ArrayList<Locality.LocalityName>();
        }
        return this.localityNames;
    }

    public PostalRouteType getPostalRoute() {
        return postalRoute;
    }

    public void setPostalRoute(PostalRouteType value) {
        this.postalRoute = ((PostalRouteTypeImpl) value);
    }

    public PostOffice getPostOffice() {
        return postOffice;
    }

    public void setPostOffice(PostOffice value) {
        this.postOffice = ((PostOfficeImpl) value);
    }

    public LargeMailUserType getLargeMailUser() {
        return largeMailUser;
    }

    public void setLargeMailUser(LargeMailUserType value) {
        this.largeMailUser = ((LargeMailUserTypeImpl) value);
    }

    public PostBox getPostBox() {
        return postBox;
    }

    public void setPostBox(PostBox value) {
        this.postBox = ((PostBoxImpl) value);
    }

    public Thoroughfare getThoroughfare() {
        return thoroughfare;
    }

    public void setThoroughfare(Thoroughfare value) {
        this.thoroughfare = ((ThoroughfareImpl) value);
    }

    public Premise getPremise() {
        return premise;
    }

    public void setPremise(Premise value) {
        this.premise = ((PremiseImpl) value);
    }

    public DependentLocalityType getDependentLocality() {
        return dependentLocality;
    }

    public void setDependentLocality(DependentLocalityType value) {
        this.dependentLocality = ((DependentLocalityTypeImpl) value);
    }

    public PostalCode getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(PostalCode value) {
        this.postalCode = ((PostalCodeImpl) value);
    }

    public List<Object> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Object>();
        }
        return this.anies;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

    public String getUsageType() {
        return usageType;
    }

    public void setUsageType(String value) {
        this.usageType = value;
    }

    public String getIndicator() {
        return indicator;
    }

    public void setIndicator(String value) {
        this.indicator = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class LocalityNameImpl
        implements Locality.LocalityName
    {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "Type")
        @XmlSchemaType(name = "anySimpleType")
        protected String type;
        @XmlAttribute(name = "Code")
        @XmlSchemaType(name = "anySimpleType")
        protected String code;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        public String getContent() {
            return content;
        }

        public void setContent(String value) {
            this.content = value;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

        public String getCode() {
            return code;
        }

        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
