//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LinkType;
import org.gpx2web.binding.kml.LocationType;
import org.gpx2web.binding.kml.ModelType;
import org.gpx2web.binding.kml.OrientationType;
import org.gpx2web.binding.kml.ResourceMapType;
import org.gpx2web.binding.kml.ScaleType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelType", propOrder = {
    "altitudeModeGroup",
    "location",
    "orientation",
    "scale",
    "link",
    "resourceMap",
    "modelSimpleExtensionGroups",
    "modelObjectExtensionGroups"
})
public class ModelTypeImpl
    extends AbstractGeometryTypeImpl
    implements ModelType
{

    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlElement(name = "Location", type = LocationTypeImpl.class)
    protected LocationTypeImpl location;
    @XmlElement(name = "Orientation", type = OrientationTypeImpl.class)
    protected OrientationTypeImpl orientation;
    @XmlElement(name = "Scale", type = ScaleTypeImpl.class)
    protected ScaleTypeImpl scale;
    @XmlElement(name = "Link", type = LinkTypeImpl.class)
    protected LinkTypeImpl link;
    @XmlElement(name = "ResourceMap", type = ResourceMapTypeImpl.class)
    protected ResourceMapTypeImpl resourceMap;
    @XmlElement(name = "ModelSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> modelSimpleExtensionGroups;
    @XmlElement(name = "ModelObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> modelObjectExtensionGroups;

    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = ((JAXBElement<?> ) value);
    }

    public LocationType getLocation() {
        return location;
    }

    public void setLocation(LocationType value) {
        this.location = ((LocationTypeImpl) value);
    }

    public OrientationType getOrientation() {
        return orientation;
    }

    public void setOrientation(OrientationType value) {
        this.orientation = ((OrientationTypeImpl) value);
    }

    public ScaleType getScale() {
        return scale;
    }

    public void setScale(ScaleType value) {
        this.scale = ((ScaleTypeImpl) value);
    }

    public LinkType getLink() {
        return link;
    }

    public void setLink(LinkType value) {
        this.link = ((LinkTypeImpl) value);
    }

    public ResourceMapType getResourceMap() {
        return resourceMap;
    }

    public void setResourceMap(ResourceMapType value) {
        this.resourceMap = ((ResourceMapTypeImpl) value);
    }

    public List<Object> getModelSimpleExtensionGroups() {
        if (modelSimpleExtensionGroups == null) {
            modelSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.modelSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getModelObjectExtensionGroups() {
        if (modelObjectExtensionGroups == null) {
            modelObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.modelObjectExtensionGroups;
    }

}
