//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractGeometryType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.MultiGeometryType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiGeometryType", propOrder = {
    "abstractGeometryGroups",
    "multiGeometrySimpleExtensionGroups",
    "multiGeometryObjectExtensionGroups"
})
public class MultiGeometryTypeImpl
    extends AbstractGeometryTypeImpl
    implements MultiGeometryType
{

    @XmlElementRef(name = "AbstractGeometryGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractGeometryType>> abstractGeometryGroups;
    @XmlElement(name = "MultiGeometrySimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> multiGeometrySimpleExtensionGroups;
    @XmlElement(name = "MultiGeometryObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> multiGeometryObjectExtensionGroups;

    public List<JAXBElement<? extends AbstractGeometryType>> getAbstractGeometryGroups() {
        if (abstractGeometryGroups == null) {
            abstractGeometryGroups = new ArrayList<JAXBElement<? extends AbstractGeometryType>>();
        }
        return this.abstractGeometryGroups;
    }

    public List<Object> getMultiGeometrySimpleExtensionGroups() {
        if (multiGeometrySimpleExtensionGroups == null) {
            multiGeometrySimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.multiGeometrySimpleExtensionGroups;
    }

    public List<AbstractObjectType> getMultiGeometryObjectExtensionGroups() {
        if (multiGeometryObjectExtensionGroups == null) {
            multiGeometryObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.multiGeometryObjectExtensionGroups;
    }

}
