//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.AbstractStyleSelectorType;
import org.gpx2web.binding.kml.PairType;
import org.gpx2web.binding.kml.StyleStateEnumType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PairType", propOrder = {
    "key",
    "styleUrl",
    "abstractStyleSelectorGroup",
    "pairSimpleExtensionGroups",
    "pairObjectExtensionGroups"
})
public class PairTypeImpl
    extends AbstractObjectTypeImpl
    implements PairType
{

    @XmlElement(defaultValue = "normal")
    protected StyleStateEnumType key;
    @XmlSchemaType(name = "anyURI")
    protected String styleUrl;
    @XmlElementRef(name = "AbstractStyleSelectorGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractStyleSelectorTypeImpl> abstractStyleSelectorGroup;
    @XmlElement(name = "PairSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> pairSimpleExtensionGroups;
    @XmlElement(name = "PairObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> pairObjectExtensionGroups;

    public StyleStateEnumType getKey() {
        return key;
    }

    public void setKey(StyleStateEnumType value) {
        this.key = value;
    }

    public String getStyleUrl() {
        return styleUrl;
    }

    public void setStyleUrl(String value) {
        this.styleUrl = value;
    }

    public JAXBElement<? extends AbstractStyleSelectorType> getAbstractStyleSelectorGroup() {
        return abstractStyleSelectorGroup;
    }

    public void setAbstractStyleSelectorGroup(JAXBElement<? extends AbstractStyleSelectorType> value) {
        this.abstractStyleSelectorGroup = ((JAXBElement<? extends AbstractStyleSelectorTypeImpl> ) value);
    }

    public List<Object> getPairSimpleExtensionGroups() {
        if (pairSimpleExtensionGroups == null) {
            pairSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.pairSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getPairObjectExtensionGroups() {
        if (pairObjectExtensionGroups == null) {
            pairObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.pairObjectExtensionGroups;
    }

}
