//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.PointType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointType", propOrder = {
    "extrude",
    "altitudeModeGroup",
    "coordinates",
    "pointSimpleExtensionGroups",
    "pointObjectExtensionGroups"
})
public class PointTypeImpl
    extends AbstractGeometryTypeImpl
    implements PointType
{

    @XmlElement(defaultValue = "0")
    protected Boolean extrude;
    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlList
    protected List<String> coordinates;
    @XmlElement(name = "PointSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> pointSimpleExtensionGroups;
    @XmlElement(name = "PointObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> pointObjectExtensionGroups;

    public Boolean isExtrude() {
        return extrude;
    }

    public void setExtrude(Boolean value) {
        this.extrude = value;
    }

    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = ((JAXBElement<?> ) value);
    }

    public List<String> getCoordinates() {
        if (coordinates == null) {
            coordinates = new ArrayList<String>();
        }
        return this.coordinates;
    }

    public List<Object> getPointSimpleExtensionGroups() {
        if (pointSimpleExtensionGroups == null) {
            pointSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.pointSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getPointObjectExtensionGroups() {
        if (pointObjectExtensionGroups == null) {
            pointObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.pointObjectExtensionGroups;
    }

}
