//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.PolyStyleType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolyStyleType", propOrder = {
    "fill",
    "outline",
    "polyStyleSimpleExtensionGroups",
    "polyStyleObjectExtensionGroups"
})
public class PolyStyleTypeImpl
    extends AbstractColorStyleTypeImpl
    implements PolyStyleType
{

    @XmlElement(defaultValue = "1")
    protected Boolean fill;
    @XmlElement(defaultValue = "1")
    protected Boolean outline;
    @XmlElement(name = "PolyStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> polyStyleSimpleExtensionGroups;
    @XmlElement(name = "PolyStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> polyStyleObjectExtensionGroups;

    public Boolean isFill() {
        return fill;
    }

    public void setFill(Boolean value) {
        this.fill = value;
    }

    public Boolean isOutline() {
        return outline;
    }

    public void setOutline(Boolean value) {
        this.outline = value;
    }

    public List<Object> getPolyStyleSimpleExtensionGroups() {
        if (polyStyleSimpleExtensionGroups == null) {
            polyStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.polyStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getPolyStyleObjectExtensionGroups() {
        if (polyStyleObjectExtensionGroups == null) {
            polyStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.polyStyleObjectExtensionGroups;
    }

}
