//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.gpx2web.binding.kml.AddressLine;
import org.gpx2web.binding.kml.BuildingNameType;
import org.gpx2web.binding.kml.FirmType;
import org.gpx2web.binding.kml.MailStopType;
import org.gpx2web.binding.kml.PostalCode;
import org.gpx2web.binding.kml.Premise;
import org.gpx2web.binding.kml.PremiseNumber;
import org.gpx2web.binding.kml.PremiseNumberPrefix;
import org.gpx2web.binding.kml.PremiseNumberSuffix;
import org.gpx2web.binding.kml.SubPremiseType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressLines",
    "premiseNames",
    "premiseNumberRange",
    "premiseNumbers",
    "premiseLocation",
    "premiseNumberPrefixes",
    "premiseNumberSuffixes",
    "buildingNames",
    "firm",
    "subPremises",
    "mailStop",
    "postalCode",
    "premise",
    "anies"
})
@XmlRootElement(name = "Premise", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0")
public class PremiseImpl
    implements Premise
{

    @XmlElement(name = "AddressLine", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = AddressLineImpl.class)
    protected List<AddressLine> addressLines;
    @XmlElement(name = "PremiseName", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseImpl.PremiseNameImpl.class)
    protected List<Premise.PremiseName> premiseNames;
    @XmlElement(name = "PremiseNumberRange", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseImpl.PremiseNumberRangeImpl.class)
    protected PremiseImpl.PremiseNumberRangeImpl premiseNumberRange;
    @XmlElement(name = "PremiseNumber", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberImpl.class)
    protected List<PremiseNumber> premiseNumbers;
    @XmlElement(name = "PremiseLocation", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseImpl.PremiseLocationImpl.class)
    protected PremiseImpl.PremiseLocationImpl premiseLocation;
    @XmlElement(name = "PremiseNumberPrefix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberPrefixImpl.class)
    protected List<PremiseNumberPrefix> premiseNumberPrefixes;
    @XmlElement(name = "PremiseNumberSuffix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberSuffixImpl.class)
    protected List<PremiseNumberSuffix> premiseNumberSuffixes;
    @XmlElement(name = "BuildingName", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = BuildingNameTypeImpl.class)
    protected List<BuildingNameType> buildingNames;
    @XmlElement(name = "Firm", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = FirmTypeImpl.class)
    protected FirmTypeImpl firm;
    @XmlElement(name = "SubPremise", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = SubPremiseTypeImpl.class)
    protected List<SubPremiseType> subPremises;
    @XmlElement(name = "MailStop", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = MailStopTypeImpl.class)
    protected MailStopTypeImpl mailStop;
    @XmlElement(name = "PostalCode", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PostalCodeImpl.class)
    protected PostalCodeImpl postalCode;
    @XmlElement(name = "Premise", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseImpl.class)
    protected PremiseImpl premise;
    @XmlAnyElement(lax = true)
    protected List<Object> anies;
    @XmlAttribute(name = "Type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute(name = "PremiseDependency")
    @XmlSchemaType(name = "anySimpleType")
    protected String premiseDependency;
    @XmlAttribute(name = "PremiseDependencyType")
    @XmlSchemaType(name = "anySimpleType")
    protected String premiseDependencyType;
    @XmlAttribute(name = "PremiseThoroughfareConnector")
    @XmlSchemaType(name = "anySimpleType")
    protected String premiseThoroughfareConnector;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    public List<AddressLine> getAddressLines() {
        if (addressLines == null) {
            addressLines = new ArrayList<AddressLine>();
        }
        return this.addressLines;
    }

    public List<Premise.PremiseName> getPremiseNames() {
        if (premiseNames == null) {
            premiseNames = new ArrayList<Premise.PremiseName>();
        }
        return this.premiseNames;
    }

    public Premise.PremiseNumberRange getPremiseNumberRange() {
        return premiseNumberRange;
    }

    public void setPremiseNumberRange(Premise.PremiseNumberRange value) {
        this.premiseNumberRange = ((PremiseImpl.PremiseNumberRangeImpl) value);
    }

    public List<PremiseNumber> getPremiseNumbers() {
        if (premiseNumbers == null) {
            premiseNumbers = new ArrayList<PremiseNumber>();
        }
        return this.premiseNumbers;
    }

    public Premise.PremiseLocation getPremiseLocation() {
        return premiseLocation;
    }

    public void setPremiseLocation(Premise.PremiseLocation value) {
        this.premiseLocation = ((PremiseImpl.PremiseLocationImpl) value);
    }

    public List<PremiseNumberPrefix> getPremiseNumberPrefixes() {
        if (premiseNumberPrefixes == null) {
            premiseNumberPrefixes = new ArrayList<PremiseNumberPrefix>();
        }
        return this.premiseNumberPrefixes;
    }

    public List<PremiseNumberSuffix> getPremiseNumberSuffixes() {
        if (premiseNumberSuffixes == null) {
            premiseNumberSuffixes = new ArrayList<PremiseNumberSuffix>();
        }
        return this.premiseNumberSuffixes;
    }

    public List<BuildingNameType> getBuildingNames() {
        if (buildingNames == null) {
            buildingNames = new ArrayList<BuildingNameType>();
        }
        return this.buildingNames;
    }

    public FirmType getFirm() {
        return firm;
    }

    public void setFirm(FirmType value) {
        this.firm = ((FirmTypeImpl) value);
    }

    public List<SubPremiseType> getSubPremises() {
        if (subPremises == null) {
            subPremises = new ArrayList<SubPremiseType>();
        }
        return this.subPremises;
    }

    public MailStopType getMailStop() {
        return mailStop;
    }

    public void setMailStop(MailStopType value) {
        this.mailStop = ((MailStopTypeImpl) value);
    }

    public PostalCode getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(PostalCode value) {
        this.postalCode = ((PostalCodeImpl) value);
    }

    public Premise getPremise() {
        return premise;
    }

    public void setPremise(Premise value) {
        this.premise = ((PremiseImpl) value);
    }

    public List<Object> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Object>();
        }
        return this.anies;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

    public String getPremiseDependency() {
        return premiseDependency;
    }

    public void setPremiseDependency(String value) {
        this.premiseDependency = value;
    }

    public String getPremiseDependencyType() {
        return premiseDependencyType;
    }

    public void setPremiseDependencyType(String value) {
        this.premiseDependencyType = value;
    }

    public String getPremiseThoroughfareConnector() {
        return premiseThoroughfareConnector;
    }

    public void setPremiseThoroughfareConnector(String value) {
        this.premiseThoroughfareConnector = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class PremiseLocationImpl
        implements Premise.PremiseLocation
    {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "Code")
        @XmlSchemaType(name = "anySimpleType")
        protected String code;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        public String getContent() {
            return content;
        }

        public void setContent(String value) {
            this.content = value;
        }

        public String getCode() {
            return code;
        }

        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class PremiseNameImpl
        implements Premise.PremiseName
    {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "Type")
        @XmlSchemaType(name = "anySimpleType")
        protected String type;
        @XmlAttribute(name = "TypeOccurrence")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String typeOccurrence;
        @XmlAttribute(name = "Code")
        @XmlSchemaType(name = "anySimpleType")
        protected String code;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        public String getContent() {
            return content;
        }

        public void setContent(String value) {
            this.content = value;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

        public String getTypeOccurrence() {
            return typeOccurrence;
        }

        public void setTypeOccurrence(String value) {
            this.typeOccurrence = value;
        }

        public String getCode() {
            return code;
        }

        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "premiseNumberRangeFrom",
        "premiseNumberRangeTo"
    })
    public static class PremiseNumberRangeImpl
        implements Premise.PremiseNumberRange
    {

        @XmlElement(name = "PremiseNumberRangeFrom", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", required = true, type = PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeFromImpl.class)
        protected PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeFromImpl premiseNumberRangeFrom;
        @XmlElement(name = "PremiseNumberRangeTo", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", required = true, type = PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeToImpl.class)
        protected PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeToImpl premiseNumberRangeTo;
        @XmlAttribute(name = "RangeType")
        @XmlSchemaType(name = "anySimpleType")
        protected String rangeType;
        @XmlAttribute(name = "Indicator")
        @XmlSchemaType(name = "anySimpleType")
        protected String indicator;
        @XmlAttribute(name = "Separator")
        @XmlSchemaType(name = "anySimpleType")
        protected String separator;
        @XmlAttribute(name = "Type")
        @XmlSchemaType(name = "anySimpleType")
        protected String type;
        @XmlAttribute(name = "IndicatorOccurence")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String indicatorOccurence;
        @XmlAttribute(name = "NumberRangeOccurence")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String numberRangeOccurence;

        public Premise.PremiseNumberRange.PremiseNumberRangeFrom getPremiseNumberRangeFrom() {
            return premiseNumberRangeFrom;
        }

        public void setPremiseNumberRangeFrom(Premise.PremiseNumberRange.PremiseNumberRangeFrom value) {
            this.premiseNumberRangeFrom = ((PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeFromImpl) value);
        }

        public Premise.PremiseNumberRange.PremiseNumberRangeTo getPremiseNumberRangeTo() {
            return premiseNumberRangeTo;
        }

        public void setPremiseNumberRangeTo(Premise.PremiseNumberRange.PremiseNumberRangeTo value) {
            this.premiseNumberRangeTo = ((PremiseImpl.PremiseNumberRangeImpl.PremiseNumberRangeToImpl) value);
        }

        public String getRangeType() {
            return rangeType;
        }

        public void setRangeType(String value) {
            this.rangeType = value;
        }

        public String getIndicator() {
            return indicator;
        }

        public void setIndicator(String value) {
            this.indicator = value;
        }

        public String getSeparator() {
            return separator;
        }

        public void setSeparator(String value) {
            this.separator = value;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

        public String getIndicatorOccurence() {
            return indicatorOccurence;
        }

        public void setIndicatorOccurence(String value) {
            this.indicatorOccurence = value;
        }

        public String getNumberRangeOccurence() {
            return numberRangeOccurence;
        }

        public void setNumberRangeOccurence(String value) {
            this.numberRangeOccurence = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressLines",
            "premiseNumberPrefixes",
            "premiseNumbers",
            "premiseNumberSuffixes"
        })
        public static class PremiseNumberRangeFromImpl
            implements Premise.PremiseNumberRange.PremiseNumberRangeFrom
        {

            @XmlElement(name = "AddressLine", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = AddressLineImpl.class)
            protected List<AddressLine> addressLines;
            @XmlElement(name = "PremiseNumberPrefix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberPrefixImpl.class)
            protected List<PremiseNumberPrefix> premiseNumberPrefixes;
            @XmlElement(name = "PremiseNumber", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", required = true, type = PremiseNumberImpl.class)
            protected List<PremiseNumber> premiseNumbers;
            @XmlElement(name = "PremiseNumberSuffix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberSuffixImpl.class)
            protected List<PremiseNumberSuffix> premiseNumberSuffixes;

            public List<AddressLine> getAddressLines() {
                if (addressLines == null) {
                    addressLines = new ArrayList<AddressLine>();
                }
                return this.addressLines;
            }

            public List<PremiseNumberPrefix> getPremiseNumberPrefixes() {
                if (premiseNumberPrefixes == null) {
                    premiseNumberPrefixes = new ArrayList<PremiseNumberPrefix>();
                }
                return this.premiseNumberPrefixes;
            }

            public List<PremiseNumber> getPremiseNumbers() {
                if (premiseNumbers == null) {
                    premiseNumbers = new ArrayList<PremiseNumber>();
                }
                return this.premiseNumbers;
            }

            public List<PremiseNumberSuffix> getPremiseNumberSuffixes() {
                if (premiseNumberSuffixes == null) {
                    premiseNumberSuffixes = new ArrayList<PremiseNumberSuffix>();
                }
                return this.premiseNumberSuffixes;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressLines",
            "premiseNumberPrefixes",
            "premiseNumbers",
            "premiseNumberSuffixes"
        })
        public static class PremiseNumberRangeToImpl
            implements Premise.PremiseNumberRange.PremiseNumberRangeTo
        {

            @XmlElement(name = "AddressLine", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = AddressLineImpl.class)
            protected List<AddressLine> addressLines;
            @XmlElement(name = "PremiseNumberPrefix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberPrefixImpl.class)
            protected List<PremiseNumberPrefix> premiseNumberPrefixes;
            @XmlElement(name = "PremiseNumber", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", required = true, type = PremiseNumberImpl.class)
            protected List<PremiseNumber> premiseNumbers;
            @XmlElement(name = "PremiseNumberSuffix", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", type = PremiseNumberSuffixImpl.class)
            protected List<PremiseNumberSuffix> premiseNumberSuffixes;

            public List<AddressLine> getAddressLines() {
                if (addressLines == null) {
                    addressLines = new ArrayList<AddressLine>();
                }
                return this.addressLines;
            }

            public List<PremiseNumberPrefix> getPremiseNumberPrefixes() {
                if (premiseNumberPrefixes == null) {
                    premiseNumberPrefixes = new ArrayList<PremiseNumberPrefix>();
                }
                return this.premiseNumberPrefixes;
            }

            public List<PremiseNumber> getPremiseNumbers() {
                if (premiseNumbers == null) {
                    premiseNumbers = new ArrayList<PremiseNumber>();
                }
                return this.premiseNumbers;
            }

            public List<PremiseNumberSuffix> getPremiseNumberSuffixes() {
                if (premiseNumberSuffixes == null) {
                    premiseNumberSuffixes = new ArrayList<PremiseNumberSuffix>();
                }
                return this.premiseNumberSuffixes;
            }

        }

    }

}
