//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LatLonAltBoxType;
import org.gpx2web.binding.kml.LodType;
import org.gpx2web.binding.kml.RegionType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegionType", propOrder = {
    "latLonAltBox",
    "lod",
    "regionSimpleExtensionGroups",
    "regionObjectExtensionGroups"
})
public class RegionTypeImpl
    extends AbstractObjectTypeImpl
    implements RegionType
{

    @XmlElement(name = "LatLonAltBox", type = LatLonAltBoxTypeImpl.class)
    protected LatLonAltBoxTypeImpl latLonAltBox;
    @XmlElement(name = "Lod", type = LodTypeImpl.class)
    protected LodTypeImpl lod;
    @XmlElement(name = "RegionSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> regionSimpleExtensionGroups;
    @XmlElement(name = "RegionObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> regionObjectExtensionGroups;

    public LatLonAltBoxType getLatLonAltBox() {
        return latLonAltBox;
    }

    public void setLatLonAltBox(LatLonAltBoxType value) {
        this.latLonAltBox = ((LatLonAltBoxTypeImpl) value);
    }

    public LodType getLod() {
        return lod;
    }

    public void setLod(LodType value) {
        this.lod = ((LodTypeImpl) value);
    }

    public List<Object> getRegionSimpleExtensionGroups() {
        if (regionSimpleExtensionGroups == null) {
            regionSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.regionSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getRegionObjectExtensionGroups() {
        if (regionObjectExtensionGroups == null) {
            regionObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.regionObjectExtensionGroups;
    }

}
