//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.AliasType;
import org.gpx2web.binding.kml.ResourceMapType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceMapType", propOrder = {
    "alias",
    "resourceMapSimpleExtensionGroups",
    "resourceMapObjectExtensionGroups"
})
public class ResourceMapTypeImpl
    extends AbstractObjectTypeImpl
    implements ResourceMapType
{

    @XmlElement(name = "Alias", type = AliasTypeImpl.class)
    protected List<AliasType> alias;
    @XmlElement(name = "ResourceMapSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> resourceMapSimpleExtensionGroups;
    @XmlElement(name = "ResourceMapObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> resourceMapObjectExtensionGroups;

    public List<AliasType> getAlias() {
        if (alias == null) {
            alias = new ArrayList<AliasType>();
        }
        return this.alias;
    }

    public List<Object> getResourceMapSimpleExtensionGroups() {
        if (resourceMapSimpleExtensionGroups == null) {
            resourceMapSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.resourceMapSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getResourceMapObjectExtensionGroups() {
        if (resourceMapObjectExtensionGroups == null) {
            resourceMapObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.resourceMapObjectExtensionGroups;
    }

}
