//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.ScreenOverlayType;
import org.gpx2web.binding.kml.Vec2Type;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreenOverlayType", propOrder = {
    "overlayXY",
    "screenXY",
    "rotationXY",
    "size",
    "rotation",
    "screenOverlaySimpleExtensionGroups",
    "screenOverlayObjectExtensionGroups"
})
public class ScreenOverlayTypeImpl
    extends AbstractOverlayTypeImpl
    implements ScreenOverlayType
{

    @XmlElement(type = Vec2TypeImpl.class)
    protected Vec2TypeImpl overlayXY;
    @XmlElement(type = Vec2TypeImpl.class)
    protected Vec2TypeImpl screenXY;
    @XmlElement(type = Vec2TypeImpl.class)
    protected Vec2TypeImpl rotationXY;
    @XmlElement(type = Vec2TypeImpl.class)
    protected Vec2TypeImpl size;
    @XmlElement(defaultValue = "0.0")
    protected Double rotation;
    @XmlElement(name = "ScreenOverlaySimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> screenOverlaySimpleExtensionGroups;
    @XmlElement(name = "ScreenOverlayObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> screenOverlayObjectExtensionGroups;

    public Vec2Type getOverlayXY() {
        return overlayXY;
    }

    public void setOverlayXY(Vec2Type value) {
        this.overlayXY = ((Vec2TypeImpl) value);
    }

    public Vec2Type getScreenXY() {
        return screenXY;
    }

    public void setScreenXY(Vec2Type value) {
        this.screenXY = ((Vec2TypeImpl) value);
    }

    public Vec2Type getRotationXY() {
        return rotationXY;
    }

    public void setRotationXY(Vec2Type value) {
        this.rotationXY = ((Vec2TypeImpl) value);
    }

    public Vec2Type getSize() {
        return size;
    }

    public void setSize(Vec2Type value) {
        this.size = ((Vec2TypeImpl) value);
    }

    public Double getRotation() {
        return rotation;
    }

    public void setRotation(Double value) {
        this.rotation = value;
    }

    public List<Object> getScreenOverlaySimpleExtensionGroups() {
        if (screenOverlaySimpleExtensionGroups == null) {
            screenOverlaySimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.screenOverlaySimpleExtensionGroups;
    }

    public List<AbstractObjectType> getScreenOverlayObjectExtensionGroups() {
        if (screenOverlayObjectExtensionGroups == null) {
            screenOverlayObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.screenOverlayObjectExtensionGroups;
    }

}
