//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.UnitsEnumType;
import org.gpx2web.binding.kml.Vec2Type;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vec2Type")
public class Vec2TypeImpl
    implements Vec2Type
{

    @XmlAttribute
    protected Double x;
    @XmlAttribute
    protected Double y;
    @XmlAttribute
    protected UnitsEnumType xunits;
    @XmlAttribute
    protected UnitsEnumType yunits;

    public double getX() {
        if (x == null) {
            return  1.0D;
        } else {
            return x;
        }
    }

    public void setX(Double value) {
        this.x = value;
    }

    public double getY() {
        if (y == null) {
            return  1.0D;
        } else {
            return y;
        }
    }

    public void setY(Double value) {
        this.y = value;
    }

    public UnitsEnumType getXunits() {
        if (xunits == null) {
            return UnitsEnumType.FRACTION;
        } else {
            return xunits;
        }
    }

    public void setXunits(UnitsEnumType value) {
        this.xunits = value;
    }

    public UnitsEnumType getYunits() {
        if (yunits == null) {
            return UnitsEnumType.FRACTION;
        } else {
            return yunits;
        }
    }

    public void setYunits(UnitsEnumType value) {
        this.yunits = value;
    }

}
