<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>cycling-tools</artifactId>
        <groupId>io.github.glandais.gpx2web</groupId>
        <version>1.2.7-SNAPSHOT</version>
    </parent>

    <artifactId>gpx-web</artifactId>

    <name>gpx2web - WEB module</name>
    <description>Java GPX tools</description>
    <url>https://github.com/glandais/gpx2web</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Gabriel Landais</name>
            <url>https://github.com/glandais</url>
        </developer>
    </developers>

    <scm>
        <url>http://github.com/glandais/gpx2web</url>
        <connection>scm:git:git://github.com/glandais/gpx2web.git</connection>
        <developerConnection>scm:git:git@github.com:glandais/gpx2web.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <quarkus.container-image.image>glandais/gpx-web:latest</quarkus.container-image.image>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.glandais.gpx2web</groupId>
            <artifactId>gpx</artifactId>
            <version>1.2.7-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-qute</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-docker</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>gpx-web</finalName>
    </build>
</project>