//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml;

import java.util.List;


/**
 * <p>Java class for ScreenOverlayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScreenOverlayType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/kml/2.2}AbstractOverlayType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}overlayXY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}screenXY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}rotationXY" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}size" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}rotation" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}ScreenOverlaySimpleExtensionGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}ScreenOverlayObjectExtensionGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ScreenOverlayType extends AbstractOverlayType
{


    /**
     * Gets the value of the overlayXY property.
     * 
     * @return
     *     possible object is
     *     {@link Vec2Type }
     *     
     */
    Vec2Type getOverlayXY();

    /**
     * Sets the value of the overlayXY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vec2Type }
     *     
     */
    void setOverlayXY(Vec2Type value);

    /**
     * Gets the value of the screenXY property.
     * 
     * @return
     *     possible object is
     *     {@link Vec2Type }
     *     
     */
    Vec2Type getScreenXY();

    /**
     * Sets the value of the screenXY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vec2Type }
     *     
     */
    void setScreenXY(Vec2Type value);

    /**
     * Gets the value of the rotationXY property.
     * 
     * @return
     *     possible object is
     *     {@link Vec2Type }
     *     
     */
    Vec2Type getRotationXY();

    /**
     * Sets the value of the rotationXY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vec2Type }
     *     
     */
    void setRotationXY(Vec2Type value);

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Vec2Type }
     *     
     */
    Vec2Type getSize();

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vec2Type }
     *     
     */
    void setSize(Vec2Type value);

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    Double getRotation();

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    void setRotation(Double value);

    /**
     * Gets the value of the screenOverlaySimpleExtensionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screenOverlaySimpleExtensionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreenOverlaySimpleExtensionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    List<Object> getScreenOverlaySimpleExtensionGroups();

    /**
     * Gets the value of the screenOverlayObjectExtensionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screenOverlayObjectExtensionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreenOverlayObjectExtensionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractObjectType }
     * 
     * 
     */
    List<AbstractObjectType> getScreenOverlayObjectExtensionGroups();

}
