//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml;

import java.util.List;


/**
 * <p>Java class for StyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StyleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/kml/2.2}AbstractStyleSelectorType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}IconStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}LabelStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}LineStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}PolyStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}BalloonStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}ListStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}StyleSimpleExtensionGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/kml/2.2}StyleObjectExtensionGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface StyleType extends AbstractStyleSelectorType
{


    /**
     * Gets the value of the iconStyle property.
     * 
     * @return
     *     possible object is
     *     {@link IconStyleType }
     *     
     */
    IconStyleType getIconStyle();

    /**
     * Sets the value of the iconStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconStyleType }
     *     
     */
    void setIconStyle(IconStyleType value);

    /**
     * Gets the value of the labelStyle property.
     * 
     * @return
     *     possible object is
     *     {@link LabelStyleType }
     *     
     */
    LabelStyleType getLabelStyle();

    /**
     * Sets the value of the labelStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelStyleType }
     *     
     */
    void setLabelStyle(LabelStyleType value);

    /**
     * Gets the value of the lineStyle property.
     * 
     * @return
     *     possible object is
     *     {@link LineStyleType }
     *     
     */
    LineStyleType getLineStyle();

    /**
     * Sets the value of the lineStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineStyleType }
     *     
     */
    void setLineStyle(LineStyleType value);

    /**
     * Gets the value of the polyStyle property.
     * 
     * @return
     *     possible object is
     *     {@link PolyStyleType }
     *     
     */
    PolyStyleType getPolyStyle();

    /**
     * Sets the value of the polyStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolyStyleType }
     *     
     */
    void setPolyStyle(PolyStyleType value);

    /**
     * Gets the value of the balloonStyle property.
     * 
     * @return
     *     possible object is
     *     {@link BalloonStyleType }
     *     
     */
    BalloonStyleType getBalloonStyle();

    /**
     * Sets the value of the balloonStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalloonStyleType }
     *     
     */
    void setBalloonStyle(BalloonStyleType value);

    /**
     * Gets the value of the listStyle property.
     * 
     * @return
     *     possible object is
     *     {@link ListStyleType }
     *     
     */
    ListStyleType getListStyle();

    /**
     * Sets the value of the listStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListStyleType }
     *     
     */
    void setListStyle(ListStyleType value);

    /**
     * Gets the value of the styleSimpleExtensionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the styleSimpleExtensionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyleSimpleExtensionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    List<Object> getStyleSimpleExtensionGroups();

    /**
     * Gets the value of the styleObjectExtensionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the styleObjectExtensionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyleObjectExtensionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractObjectType }
     * 
     * 
     */
    List<AbstractObjectType> getStyleObjectExtensionGroups();

}
