//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml;



/**
 * <p>Java class for vec2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vec2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" default="1.0" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" default="1.0" />
 *       &lt;attribute name="xunits" type="{http://www.opengis.net/kml/2.2}unitsEnumType" default="fraction" />
 *       &lt;attribute name="yunits" type="{http://www.opengis.net/kml/2.2}unitsEnumType" default="fraction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface Vec2Type {


    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    double getX();

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    void setX(Double value);

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    double getY();

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    void setY(Double value);

    /**
     * Gets the value of the xunits property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsEnumType }
     *     
     */
    UnitsEnumType getXunits();

    /**
     * Sets the value of the xunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsEnumType }
     *     
     */
    void setXunits(UnitsEnumType value);

    /**
     * Gets the value of the yunits property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsEnumType }
     *     
     */
    UnitsEnumType getYunits();

    /**
     * Sets the value of the yunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsEnumType }
     *     
     */
    void setYunits(UnitsEnumType value);

}
