//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.AbstractSubStyleType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractSubStyleType", propOrder = {
    "abstractSubStyleSimpleExtensionGroups",
    "abstractSubStyleObjectExtensionGroups"
})
@XmlSeeAlso({
    ListStyleTypeImpl.class,
    BalloonStyleTypeImpl.class,
    AbstractColorStyleTypeImpl.class
})
public abstract class AbstractSubStyleTypeImpl
    extends AbstractObjectTypeImpl
    implements AbstractSubStyleType
{

    @XmlElement(name = "AbstractSubStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> abstractSubStyleSimpleExtensionGroups;
    @XmlElement(name = "AbstractSubStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> abstractSubStyleObjectExtensionGroups;

    public List<Object> getAbstractSubStyleSimpleExtensionGroups() {
        if (abstractSubStyleSimpleExtensionGroups == null) {
            abstractSubStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.abstractSubStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getAbstractSubStyleObjectExtensionGroups() {
        if (abstractSubStyleObjectExtensionGroups == null) {
            abstractSubStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.abstractSubStyleObjectExtensionGroups;
    }

}
