//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.gpx2web.binding.kml.AbstractColorStyleType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.ColorModeEnumType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractColorStyleType", propOrder = {
    "color",
    "colorMode",
    "abstractColorStyleSimpleExtensionGroups",
    "abstractColorStyleObjectExtensionGroups"
})
@XmlSeeAlso({
    IconStyleTypeImpl.class,
    LabelStyleTypeImpl.class,
    LineStyleTypeImpl.class,
    PolyStyleTypeImpl.class
})
public abstract class AbstractColorStyleTypeImpl
    extends AbstractSubStyleTypeImpl
    implements AbstractColorStyleType
{

    @XmlElement(type = String.class, defaultValue = "ffffffff")
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] color;
    @XmlElement(defaultValue = "normal")
    protected ColorModeEnumType colorMode;
    @XmlElement(name = "AbstractColorStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> abstractColorStyleSimpleExtensionGroups;
    @XmlElement(name = "AbstractColorStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> abstractColorStyleObjectExtensionGroups;

    public byte[] getColor() {
        return color;
    }

    public void setColor(byte[] value) {
        this.color = ((byte[]) value);
    }

    public ColorModeEnumType getColorMode() {
        return colorMode;
    }

    public void setColorMode(ColorModeEnumType value) {
        this.colorMode = value;
    }

    public List<Object> getAbstractColorStyleSimpleExtensionGroups() {
        if (abstractColorStyleSimpleExtensionGroups == null) {
            abstractColorStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.abstractColorStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getAbstractColorStyleObjectExtensionGroups() {
        if (abstractColorStyleObjectExtensionGroups == null) {
            abstractColorStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.abstractColorStyleObjectExtensionGroups;
    }

}
