//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.BasicLinkType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicLinkType", propOrder = {
    "href",
    "basicLinkSimpleExtensionGroups",
    "basicLinkObjectExtensionGroups"
})
@XmlSeeAlso({
    LinkTypeImpl.class
})
public class BasicLinkTypeImpl
    extends AbstractObjectTypeImpl
    implements BasicLinkType
{

    protected String href;
    @XmlElement(name = "BasicLinkSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> basicLinkSimpleExtensionGroups;
    @XmlElement(name = "BasicLinkObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> basicLinkObjectExtensionGroups;

    public String getHref() {
        return href;
    }

    public void setHref(String value) {
        this.href = value;
    }

    public List<Object> getBasicLinkSimpleExtensionGroups() {
        if (basicLinkSimpleExtensionGroups == null) {
            basicLinkSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.basicLinkSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getBasicLinkObjectExtensionGroups() {
        if (basicLinkObjectExtensionGroups == null) {
            basicLinkObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.basicLinkObjectExtensionGroups;
    }

}
