//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.BoundaryType;
import org.gpx2web.binding.kml.LinearRingType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundaryType", propOrder = {
    "linearRing",
    "boundarySimpleExtensionGroups",
    "boundaryObjectExtensionGroups"
})
public class BoundaryTypeImpl
    implements BoundaryType
{

    @XmlElement(name = "LinearRing", type = LinearRingTypeImpl.class)
    protected LinearRingTypeImpl linearRing;
    @XmlElement(name = "BoundarySimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> boundarySimpleExtensionGroups;
    @XmlElement(name = "BoundaryObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> boundaryObjectExtensionGroups;

    public LinearRingType getLinearRing() {
        return linearRing;
    }

    public void setLinearRing(LinearRingType value) {
        this.linearRing = ((LinearRingTypeImpl) value);
    }

    public List<Object> getBoundarySimpleExtensionGroups() {
        if (boundarySimpleExtensionGroups == null) {
            boundarySimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.boundarySimpleExtensionGroups;
    }

    public List<AbstractObjectType> getBoundaryObjectExtensionGroups() {
        if (boundaryObjectExtensionGroups == null) {
            boundaryObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.boundaryObjectExtensionGroups;
    }

}
