//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.CameraType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CameraType", propOrder = {
    "longitude",
    "latitude",
    "altitude",
    "heading",
    "tilt",
    "roll",
    "altitudeModeGroup",
    "cameraSimpleExtensionGroups",
    "cameraObjectExtensionGroups"
})
public class CameraTypeImpl
    extends AbstractViewTypeImpl
    implements CameraType
{

    @XmlElement(defaultValue = "0.0")
    protected Double longitude;
    @XmlElement(defaultValue = "0.0")
    protected Double latitude;
    @XmlElement(defaultValue = "0.0")
    protected Double altitude;
    @XmlElement(defaultValue = "0.0")
    protected Double heading;
    @XmlElement(defaultValue = "0.0")
    protected Double tilt;
    @XmlElement(defaultValue = "0.0")
    protected Double roll;
    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlElement(name = "CameraSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> cameraSimpleExtensionGroups;
    @XmlElement(name = "CameraObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> cameraObjectExtensionGroups;

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double value) {
        this.longitude = value;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double value) {
        this.latitude = value;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double value) {
        this.altitude = value;
    }

    public Double getHeading() {
        return heading;
    }

    public void setHeading(Double value) {
        this.heading = value;
    }

    public Double getTilt() {
        return tilt;
    }

    public void setTilt(Double value) {
        this.tilt = value;
    }

    public Double getRoll() {
        return roll;
    }

    public void setRoll(Double value) {
        this.roll = value;
    }

    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = ((JAXBElement<?> ) value);
    }

    public List<Object> getCameraSimpleExtensionGroups() {
        if (cameraSimpleExtensionGroups == null) {
            cameraSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.cameraSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getCameraObjectExtensionGroups() {
        if (cameraObjectExtensionGroups == null) {
            cameraObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.cameraObjectExtensionGroups;
    }

}
