//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.GroundOverlayType;
import org.gpx2web.binding.kml.LatLonBoxType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroundOverlayType", propOrder = {
    "altitude",
    "altitudeModeGroup",
    "latLonBox",
    "groundOverlaySimpleExtensionGroups",
    "groundOverlayObjectExtensionGroups"
})
public class GroundOverlayTypeImpl
    extends AbstractOverlayTypeImpl
    implements GroundOverlayType
{

    @XmlElement(defaultValue = "0.0")
    protected Double altitude;
    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlElement(name = "LatLonBox", type = LatLonBoxTypeImpl.class)
    protected LatLonBoxTypeImpl latLonBox;
    @XmlElement(name = "GroundOverlaySimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> groundOverlaySimpleExtensionGroups;
    @XmlElement(name = "GroundOverlayObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> groundOverlayObjectExtensionGroups;

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double value) {
        this.altitude = value;
    }

    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = ((JAXBElement<?> ) value);
    }

    public LatLonBoxType getLatLonBox() {
        return latLonBox;
    }

    public void setLatLonBox(LatLonBoxType value) {
        this.latLonBox = ((LatLonBoxTypeImpl) value);
    }

    public List<Object> getGroundOverlaySimpleExtensionGroups() {
        if (groundOverlaySimpleExtensionGroups == null) {
            groundOverlaySimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.groundOverlaySimpleExtensionGroups;
    }

    public List<AbstractObjectType> getGroundOverlayObjectExtensionGroups() {
        if (groundOverlayObjectExtensionGroups == null) {
            groundOverlayObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.groundOverlayObjectExtensionGroups;
    }

}
