//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractFeatureType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.Kml;
import org.gpx2web.binding.kml.NetworkLinkControl;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KmlType", propOrder = {
    "networkLinkControl",
    "abstractFeatureGroup",
    "kmlSimpleExtensionGroups",
    "kmlObjectExtensionGroups"
})
@XmlRootElement(name = "kml")
public class KmlImpl
    implements Kml
{

    @XmlElement(name = "NetworkLinkControl", type = NetworkLinkControlImpl.class)
    protected NetworkLinkControlImpl networkLinkControl;
    @XmlElementRef(name = "AbstractFeatureGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractFeatureTypeImpl> abstractFeatureGroup;
    @XmlElement(name = "KmlSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> kmlSimpleExtensionGroups;
    @XmlElement(name = "KmlObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> kmlObjectExtensionGroups;
    @XmlAttribute
    protected String hint;

    public NetworkLinkControl getNetworkLinkControl() {
        return networkLinkControl;
    }

    public void setNetworkLinkControl(NetworkLinkControl value) {
        this.networkLinkControl = ((NetworkLinkControlImpl) value);
    }

    public JAXBElement<? extends AbstractFeatureType> getAbstractFeatureGroup() {
        return abstractFeatureGroup;
    }

    public void setAbstractFeatureGroup(JAXBElement<? extends AbstractFeatureType> value) {
        this.abstractFeatureGroup = ((JAXBElement<? extends AbstractFeatureTypeImpl> ) value);
    }

    public List<Object> getKmlSimpleExtensionGroups() {
        if (kmlSimpleExtensionGroups == null) {
            kmlSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.kmlSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getKmlObjectExtensionGroups() {
        if (kmlObjectExtensionGroups == null) {
            kmlObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.kmlObjectExtensionGroups;
    }

    public String getHint() {
        return hint;
    }

    public void setHint(String value) {
        this.hint = value;
    }

}
