//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LineStringType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineStringType", propOrder = {
    "extrude",
    "tessellate",
    "altitudeModeGroup",
    "coordinates",
    "lineStringSimpleExtensionGroups",
    "lineStringObjectExtensionGroups"
})
public class LineStringTypeImpl
    extends AbstractGeometryTypeImpl
    implements LineStringType
{

    @XmlElement(defaultValue = "0")
    protected Boolean extrude;
    @XmlElement(defaultValue = "0")
    protected Boolean tessellate;
    @XmlElementRef(name = "altitudeModeGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<?> altitudeModeGroup;
    @XmlList
    protected List<String> coordinates;
    @XmlElement(name = "LineStringSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> lineStringSimpleExtensionGroups;
    @XmlElement(name = "LineStringObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> lineStringObjectExtensionGroups;

    public Boolean isExtrude() {
        return extrude;
    }

    public void setExtrude(Boolean value) {
        this.extrude = value;
    }

    public Boolean isTessellate() {
        return tessellate;
    }

    public void setTessellate(Boolean value) {
        this.tessellate = value;
    }

    public JAXBElement<?> getAltitudeModeGroup() {
        return altitudeModeGroup;
    }

    public void setAltitudeModeGroup(JAXBElement<?> value) {
        this.altitudeModeGroup = ((JAXBElement<?> ) value);
    }

    public List<String> getCoordinates() {
        if (coordinates == null) {
            coordinates = new ArrayList<String>();
        }
        return this.coordinates;
    }

    public List<Object> getLineStringSimpleExtensionGroups() {
        if (lineStringSimpleExtensionGroups == null) {
            lineStringSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.lineStringSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getLineStringObjectExtensionGroups() {
        if (lineStringObjectExtensionGroups == null) {
            lineStringObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.lineStringObjectExtensionGroups;
    }

}
