//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LinkType;
import org.gpx2web.binding.kml.RefreshModeEnumType;
import org.gpx2web.binding.kml.ViewRefreshModeEnumType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkType", propOrder = {
    "refreshMode",
    "refreshInterval",
    "viewRefreshMode",
    "viewRefreshTime",
    "viewBoundScale",
    "viewFormat",
    "httpQuery",
    "linkSimpleExtensionGroups",
    "linkObjectExtensionGroups"
})
public class LinkTypeImpl
    extends BasicLinkTypeImpl
    implements LinkType
{

    @XmlElement(defaultValue = "onChange")
    protected RefreshModeEnumType refreshMode;
    @XmlElement(defaultValue = "4.0")
    protected Double refreshInterval;
    @XmlElement(defaultValue = "never")
    protected ViewRefreshModeEnumType viewRefreshMode;
    @XmlElement(defaultValue = "4.0")
    protected Double viewRefreshTime;
    @XmlElement(defaultValue = "1.0")
    protected Double viewBoundScale;
    protected String viewFormat;
    protected String httpQuery;
    @XmlElement(name = "LinkSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> linkSimpleExtensionGroups;
    @XmlElement(name = "LinkObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> linkObjectExtensionGroups;

    public RefreshModeEnumType getRefreshMode() {
        return refreshMode;
    }

    public void setRefreshMode(RefreshModeEnumType value) {
        this.refreshMode = value;
    }

    public Double getRefreshInterval() {
        return refreshInterval;
    }

    public void setRefreshInterval(Double value) {
        this.refreshInterval = value;
    }

    public ViewRefreshModeEnumType getViewRefreshMode() {
        return viewRefreshMode;
    }

    public void setViewRefreshMode(ViewRefreshModeEnumType value) {
        this.viewRefreshMode = value;
    }

    public Double getViewRefreshTime() {
        return viewRefreshTime;
    }

    public void setViewRefreshTime(Double value) {
        this.viewRefreshTime = value;
    }

    public Double getViewBoundScale() {
        return viewBoundScale;
    }

    public void setViewBoundScale(Double value) {
        this.viewBoundScale = value;
    }

    public String getViewFormat() {
        return viewFormat;
    }

    public void setViewFormat(String value) {
        this.viewFormat = value;
    }

    public String getHttpQuery() {
        return httpQuery;
    }

    public void setHttpQuery(String value) {
        this.httpQuery = value;
    }

    public List<Object> getLinkSimpleExtensionGroups() {
        if (linkSimpleExtensionGroups == null) {
            linkSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.linkSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getLinkObjectExtensionGroups() {
        if (linkObjectExtensionGroups == null) {
            linkObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.linkObjectExtensionGroups;
    }

}
