//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.ItemIconType;
import org.gpx2web.binding.kml.ListItemTypeEnumType;
import org.gpx2web.binding.kml.ListStyleType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListStyleType", propOrder = {
    "listItemType",
    "bgColor",
    "itemIcons",
    "maxSnippetLines",
    "listStyleSimpleExtensionGroups",
    "listStyleObjectExtensionGroups"
})
public class ListStyleTypeImpl
    extends AbstractSubStyleTypeImpl
    implements ListStyleType
{

    @XmlElement(defaultValue = "check")
    protected ListItemTypeEnumType listItemType;
    @XmlElement(type = String.class, defaultValue = "ffffffff")
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] bgColor;
    @XmlElement(name = "ItemIcon", type = ItemIconTypeImpl.class)
    protected List<ItemIconType> itemIcons;
    @XmlElement(defaultValue = "2")
    protected Integer maxSnippetLines;
    @XmlElement(name = "ListStyleSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> listStyleSimpleExtensionGroups;
    @XmlElement(name = "ListStyleObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> listStyleObjectExtensionGroups;

    public ListItemTypeEnumType getListItemType() {
        return listItemType;
    }

    public void setListItemType(ListItemTypeEnumType value) {
        this.listItemType = value;
    }

    public byte[] getBgColor() {
        return bgColor;
    }

    public void setBgColor(byte[] value) {
        this.bgColor = ((byte[]) value);
    }

    public List<ItemIconType> getItemIcons() {
        if (itemIcons == null) {
            itemIcons = new ArrayList<ItemIconType>();
        }
        return this.itemIcons;
    }

    public Integer getMaxSnippetLines() {
        return maxSnippetLines;
    }

    public void setMaxSnippetLines(Integer value) {
        this.maxSnippetLines = value;
    }

    public List<Object> getListStyleSimpleExtensionGroups() {
        if (listStyleSimpleExtensionGroups == null) {
            listStyleSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.listStyleSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getListStyleObjectExtensionGroups() {
        if (listStyleObjectExtensionGroups == null) {
            listStyleObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.listStyleObjectExtensionGroups;
    }

}
