//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LocationType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", propOrder = {
    "longitude",
    "latitude",
    "altitude",
    "locationSimpleExtensionGroups",
    "locationObjectExtensionGroups"
})
public class LocationTypeImpl
    extends AbstractObjectTypeImpl
    implements LocationType
{

    @XmlElement(defaultValue = "0.0")
    protected Double longitude;
    @XmlElement(defaultValue = "0.0")
    protected Double latitude;
    @XmlElement(defaultValue = "0.0")
    protected Double altitude;
    @XmlElement(name = "LocationSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> locationSimpleExtensionGroups;
    @XmlElement(name = "LocationObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> locationObjectExtensionGroups;

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double value) {
        this.longitude = value;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double value) {
        this.latitude = value;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double value) {
        this.altitude = value;
    }

    public List<Object> getLocationSimpleExtensionGroups() {
        if (locationSimpleExtensionGroups == null) {
            locationSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.locationSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getLocationObjectExtensionGroups() {
        if (locationObjectExtensionGroups == null) {
            locationObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.locationObjectExtensionGroups;
    }

}
