//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.LodType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LodType", propOrder = {
    "minLodPixels",
    "maxLodPixels",
    "minFadeExtent",
    "maxFadeExtent",
    "lodSimpleExtensionGroups",
    "lodObjectExtensionGroups"
})
public class LodTypeImpl
    extends AbstractObjectTypeImpl
    implements LodType
{

    @XmlElement(defaultValue = "0.0")
    protected Double minLodPixels;
    @XmlElement(defaultValue = "-1.0")
    protected Double maxLodPixels;
    @XmlElement(defaultValue = "0.0")
    protected Double minFadeExtent;
    @XmlElement(defaultValue = "0.0")
    protected Double maxFadeExtent;
    @XmlElement(name = "LodSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> lodSimpleExtensionGroups;
    @XmlElement(name = "LodObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> lodObjectExtensionGroups;

    public Double getMinLodPixels() {
        return minLodPixels;
    }

    public void setMinLodPixels(Double value) {
        this.minLodPixels = value;
    }

    public Double getMaxLodPixels() {
        return maxLodPixels;
    }

    public void setMaxLodPixels(Double value) {
        this.maxLodPixels = value;
    }

    public Double getMinFadeExtent() {
        return minFadeExtent;
    }

    public void setMinFadeExtent(Double value) {
        this.minFadeExtent = value;
    }

    public Double getMaxFadeExtent() {
        return maxFadeExtent;
    }

    public void setMaxFadeExtent(Double value) {
        this.maxFadeExtent = value;
    }

    public List<Object> getLodSimpleExtensionGroups() {
        if (lodSimpleExtensionGroups == null) {
            lodSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.lodSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getLodObjectExtensionGroups() {
        if (lodObjectExtensionGroups == null) {
            lodObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.lodObjectExtensionGroups;
    }

}
