//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.AbstractViewType;
import org.gpx2web.binding.kml.NetworkLinkControl;
import org.gpx2web.binding.kml.SnippetType;
import org.gpx2web.binding.kml.Update;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkLinkControlType", propOrder = {
    "minRefreshPeriod",
    "maxSessionLength",
    "cookie",
    "message",
    "linkName",
    "linkDescription",
    "linkSnippet",
    "expires",
    "update",
    "abstractViewGroup",
    "networkLinkControlSimpleExtensionGroups",
    "networkLinkControlObjectExtensionGroups"
})
@XmlRootElement(name = "NetworkLinkControl")
public class NetworkLinkControlImpl
    implements NetworkLinkControl
{

    @XmlElement(defaultValue = "0.0")
    protected Double minRefreshPeriod;
    @XmlElement(defaultValue = "-1.0")
    protected Double maxSessionLength;
    protected String cookie;
    protected String message;
    protected String linkName;
    protected String linkDescription;
    @XmlElement(type = SnippetTypeImpl.class)
    protected SnippetTypeImpl linkSnippet;
    protected String expires;
    @XmlElement(name = "Update", type = UpdateImpl.class)
    protected UpdateImpl update;
    @XmlElementRef(name = "AbstractViewGroup", namespace = "http://www.opengis.net/kml/2.2", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractViewTypeImpl> abstractViewGroup;
    @XmlElement(name = "NetworkLinkControlSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> networkLinkControlSimpleExtensionGroups;
    @XmlElement(name = "NetworkLinkControlObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> networkLinkControlObjectExtensionGroups;

    public Double getMinRefreshPeriod() {
        return minRefreshPeriod;
    }

    public void setMinRefreshPeriod(Double value) {
        this.minRefreshPeriod = value;
    }

    public Double getMaxSessionLength() {
        return maxSessionLength;
    }

    public void setMaxSessionLength(Double value) {
        this.maxSessionLength = value;
    }

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String value) {
        this.cookie = value;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String value) {
        this.message = value;
    }

    public String getLinkName() {
        return linkName;
    }

    public void setLinkName(String value) {
        this.linkName = value;
    }

    public String getLinkDescription() {
        return linkDescription;
    }

    public void setLinkDescription(String value) {
        this.linkDescription = value;
    }

    public SnippetType getLinkSnippet() {
        return linkSnippet;
    }

    public void setLinkSnippet(SnippetType value) {
        this.linkSnippet = ((SnippetTypeImpl) value);
    }

    public String getExpires() {
        return expires;
    }

    public void setExpires(String value) {
        this.expires = value;
    }

    public Update getUpdate() {
        return update;
    }

    public void setUpdate(Update value) {
        this.update = ((UpdateImpl) value);
    }

    public JAXBElement<? extends AbstractViewType> getAbstractViewGroup() {
        return abstractViewGroup;
    }

    public void setAbstractViewGroup(JAXBElement<? extends AbstractViewType> value) {
        this.abstractViewGroup = ((JAXBElement<? extends AbstractViewTypeImpl> ) value);
    }

    public List<Object> getNetworkLinkControlSimpleExtensionGroups() {
        if (networkLinkControlSimpleExtensionGroups == null) {
            networkLinkControlSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.networkLinkControlSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getNetworkLinkControlObjectExtensionGroups() {
        if (networkLinkControlObjectExtensionGroups == null) {
            networkLinkControlObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.networkLinkControlObjectExtensionGroups;
    }

}
