//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.ImagePyramidType;
import org.gpx2web.binding.kml.PhotoOverlayType;
import org.gpx2web.binding.kml.PointType;
import org.gpx2web.binding.kml.ShapeEnumType;
import org.gpx2web.binding.kml.ViewVolumeType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhotoOverlayType", propOrder = {
    "rotation",
    "viewVolume",
    "imagePyramid",
    "point",
    "shape",
    "photoOverlaySimpleExtensionGroups",
    "photoOverlayObjectExtensionGroups"
})
public class PhotoOverlayTypeImpl
    extends AbstractOverlayTypeImpl
    implements PhotoOverlayType
{

    @XmlElement(defaultValue = "0.0")
    protected Double rotation;
    @XmlElement(name = "ViewVolume", type = ViewVolumeTypeImpl.class)
    protected ViewVolumeTypeImpl viewVolume;
    @XmlElement(name = "ImagePyramid", type = ImagePyramidTypeImpl.class)
    protected ImagePyramidTypeImpl imagePyramid;
    @XmlElement(name = "Point", type = PointTypeImpl.class)
    protected PointTypeImpl point;
    @XmlElement(defaultValue = "rectangle")
    protected ShapeEnumType shape;
    @XmlElement(name = "PhotoOverlaySimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> photoOverlaySimpleExtensionGroups;
    @XmlElement(name = "PhotoOverlayObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> photoOverlayObjectExtensionGroups;

    public Double getRotation() {
        return rotation;
    }

    public void setRotation(Double value) {
        this.rotation = value;
    }

    public ViewVolumeType getViewVolume() {
        return viewVolume;
    }

    public void setViewVolume(ViewVolumeType value) {
        this.viewVolume = ((ViewVolumeTypeImpl) value);
    }

    public ImagePyramidType getImagePyramid() {
        return imagePyramid;
    }

    public void setImagePyramid(ImagePyramidType value) {
        this.imagePyramid = ((ImagePyramidTypeImpl) value);
    }

    public PointType getPoint() {
        return point;
    }

    public void setPoint(PointType value) {
        this.point = ((PointTypeImpl) value);
    }

    public ShapeEnumType getShape() {
        return shape;
    }

    public void setShape(ShapeEnumType value) {
        this.shape = value;
    }

    public List<Object> getPhotoOverlaySimpleExtensionGroups() {
        if (photoOverlaySimpleExtensionGroups == null) {
            photoOverlaySimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.photoOverlaySimpleExtensionGroups;
    }

    public List<AbstractObjectType> getPhotoOverlayObjectExtensionGroups() {
        if (photoOverlayObjectExtensionGroups == null) {
            photoOverlayObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.photoOverlayObjectExtensionGroups;
    }

}
