//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.gpx2web.binding.kml.Schema;
import org.gpx2web.binding.kml.SimpleField;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchemaType", propOrder = {
    "simpleFields",
    "schemaExtensions"
})
@XmlRootElement(name = "Schema")
public class SchemaImpl
    implements Schema
{

    @XmlElement(name = "SimpleField", type = SimpleFieldImpl.class)
    protected List<SimpleField> simpleFields;
    @XmlElement(name = "SchemaExtension")
    protected List<Object> schemaExtensions;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    public List<SimpleField> getSimpleFields() {
        if (simpleFields == null) {
            simpleFields = new ArrayList<SimpleField>();
        }
        return this.simpleFields;
    }

    public List<Object> getSchemaExtensions() {
        if (schemaExtensions == null) {
            schemaExtensions = new ArrayList<Object>();
        }
        return this.schemaExtensions;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
