//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.Update;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateType", propOrder = {
    "targetHref",
    "createsAndDeletesAndChanges",
    "updateExtensionGroups"
})
@XmlRootElement(name = "Update")
public class UpdateImpl
    implements Update
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetHref;
    @XmlElements({
        @XmlElement(name = "Change", type = ChangeImpl.class),
        @XmlElement(name = "Delete", type = DeleteImpl.class),
        @XmlElement(name = "UpdateOpExtensionGroup"),
        @XmlElement(name = "Create", type = CreateImpl.class)
    })
    protected List<Object> createsAndDeletesAndChanges;
    @XmlElement(name = "UpdateExtensionGroup")
    protected List<Object> updateExtensionGroups;

    public String getTargetHref() {
        return targetHref;
    }

    public void setTargetHref(String value) {
        this.targetHref = value;
    }

    public List<Object> getCreatesAndDeletesAndChanges() {
        if (createsAndDeletesAndChanges == null) {
            createsAndDeletesAndChanges = new ArrayList<Object>();
        }
        return this.createsAndDeletesAndChanges;
    }

    public List<Object> getUpdateExtensionGroups() {
        if (updateExtensionGroups == null) {
            updateExtensionGroups = new ArrayList<Object>();
        }
        return this.updateExtensionGroups;
    }

}
