//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 04:04:36 PM CEST 
//


package org.gpx2web.binding.kml.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.gpx2web.binding.kml.AbstractObjectType;
import org.gpx2web.binding.kml.ViewVolumeType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewVolumeType", propOrder = {
    "leftFov",
    "rightFov",
    "bottomFov",
    "topFov",
    "near",
    "viewVolumeSimpleExtensionGroups",
    "viewVolumeObjectExtensionGroups"
})
public class ViewVolumeTypeImpl
    extends AbstractObjectTypeImpl
    implements ViewVolumeType
{

    @XmlElement(defaultValue = "0.0")
    protected Double leftFov;
    @XmlElement(defaultValue = "0.0")
    protected Double rightFov;
    @XmlElement(defaultValue = "0.0")
    protected Double bottomFov;
    @XmlElement(defaultValue = "0.0")
    protected Double topFov;
    @XmlElement(defaultValue = "0.0")
    protected Double near;
    @XmlElement(name = "ViewVolumeSimpleExtensionGroup")
    @XmlSchemaType(name = "anySimpleType")
    protected List<Object> viewVolumeSimpleExtensionGroups;
    @XmlElement(name = "ViewVolumeObjectExtensionGroup", type = AbstractObjectTypeImpl.class)
    protected List<AbstractObjectType> viewVolumeObjectExtensionGroups;

    public Double getLeftFov() {
        return leftFov;
    }

    public void setLeftFov(Double value) {
        this.leftFov = value;
    }

    public Double getRightFov() {
        return rightFov;
    }

    public void setRightFov(Double value) {
        this.rightFov = value;
    }

    public Double getBottomFov() {
        return bottomFov;
    }

    public void setBottomFov(Double value) {
        this.bottomFov = value;
    }

    public Double getTopFov() {
        return topFov;
    }

    public void setTopFov(Double value) {
        this.topFov = value;
    }

    public Double getNear() {
        return near;
    }

    public void setNear(Double value) {
        this.near = value;
    }

    public List<Object> getViewVolumeSimpleExtensionGroups() {
        if (viewVolumeSimpleExtensionGroups == null) {
            viewVolumeSimpleExtensionGroups = new ArrayList<Object>();
        }
        return this.viewVolumeSimpleExtensionGroups;
    }

    public List<AbstractObjectType> getViewVolumeObjectExtensionGroups() {
        if (viewVolumeObjectExtensionGroups == null) {
            viewVolumeObjectExtensionGroups = new ArrayList<AbstractObjectType>();
        }
        return this.viewVolumeObjectExtensionGroups;
    }

}
