name: master

on:
  push:
    branches:
      - "master"
      - "spring"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Modify versions
        run: ./mvnw -B versions:set -DremoveSnapshot versions:commit
      - name: Get version
        id: get_version
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
      - name: Publish package
        run: ./mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: ./mvnw -B package -Pnative --file pom.xml
      - name: push_release
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Release ${{ steps.get_version.outputs.version }}'
          tagging_message: "v${{ steps.get_version.outputs.version }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            **/gpxtools-*-runner
      - name: Modify versions
        run: ./mvnw -B versions:set -DnextSnapshot versions:commit
      - name: push_snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Next SNAPSHOT'
