<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.glandais.gpx2web</groupId>
        <artifactId>cycling-tools</artifactId>
        <version>1.2.7</version>
    </parent>

    <artifactId>gpx</artifactId>

    <name>gpx2web - GPX module</name>
    <description>Java GPX tools</description>
    <url>https://github.com/glandais/gpx2web</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Gabriel Landais</name>
            <url>https://github.com/glandais</url>
        </developer>
    </developers>

    <scm>
        <url>http://github.com/glandais/gpx2web</url>
        <connection>scm:git:git://github.com/glandais/gpx2web.git</connection>
        <developerConnection>scm:git:git@github.com:glandais/gpx2web.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.garmin</groupId>
            <artifactId>fit</artifactId>
        </dependency>
        <dependency>
            <groupId>com.graphhopper</groupId>
            <artifactId>graphhopper-core</artifactId>
        </dependency>
        <dependency>
            <groupId>net.iakovlev</groupId>
            <artifactId>timeshape</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.haifengl</groupId>
            <artifactId>smile-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>eu.lestard</groupId>
            <artifactId>easy-di</artifactId>
            <version>0.6.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
